#!/usr/bin/python
import sys
import webbrowser
from json2html import *

style="""
<style type='text/css'>
* {
    font-family: Roboto;
    margin: 0px;
}

h1 {
    margin: 20px;
}

.ps {
    color: #888;
    margin-right: 10px;
}

table {
    /* border-collapse: collapse; */
    border-collapse: separate;
    border-spacing: 0px;
    vertical-align: middle;
    margin: 20px;

}

th, td {
    border: 1px solid black;
    padding: 5px 8px;
}

th {
    background-color: #222;
    color: white;
    position: sticky;
    border-left: 1px solid #888;
    border-right: 1px solid #888;
    top: 0;
}

th:last-child {
    border-right: 1px solid black;
}

th:first-child {
    border-left: 1px solid black;
}

/* Stripes */
tr:nth-child(even) {
    background-color: #fafafa;
}

tr:nth-child(odd) {
    background-color: #efefef;
}


</style>
"""


input=""
for line in sys.stdin:
    input+=line
table = json2html.convert(json = input)

f = open("/tmp/file.html","w+")
f.write(style)

# Writing piped data
for line in table:
    f.write(line)
f.close()

webbrowser.open("/tmp/file.html")
